package com.wos.giftredeemer;
import android.content.*;import android.database.Cursor;import android.database.sqlite.*;import java.util.*;
public final class AppDatabase extends SQLiteOpenHelper {
 public static final class CodeRow {public final long id;public final String code,status;public final long firstSeen,lastSeen;CodeRow(long i,String c,long f,long l,String s){id=i;code=c;firstSeen=f;lastSeen=l;status=s;}}
 public static final class RunRow {public final long id,started,finished;public final String status,source;public final int total,success,received,failed,network,skipped;RunRow(long i,long a,long b,String st,String so,int t,int s,int r,int f,int n,int k){id=i;started=a;finished=b;status=st;source=so;total=t;success=s;received=r;failed=f;network=n;skipped=k;}}
 public static final class AttemptRow {public final String account,player,state,code,result,message,technical;public final Integer serverCode;public final long time;AttemptRow(String a,String p,String s,String c,String r,Integer sc,String m,String te,long t){account=a;player=p;state=s;code=c;result=r;serverCode=sc;message=m;technical=te;time=t;}}
 public AppDatabase(Context c){super(c,"giftcodes.db",null,4);}
 @Override public void onCreate(SQLiteDatabase d){createV4(d);}
 private void createV4(SQLiteDatabase d){
  d.execSQL("CREATE TABLE IF NOT EXISTS accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,player_id TEXT NOT NULL,state TEXT NOT NULL,selected INTEGER NOT NULL DEFAULT 1,UNIQUE(player_id,state))");
  d.execSQL("CREATE TABLE IF NOT EXISTS gift_codes(id INTEGER PRIMARY KEY AUTOINCREMENT,code TEXT NOT NULL UNIQUE,first_seen_ms INTEGER NOT NULL,last_seen_ms INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'active')");
  d.execSQL("CREATE TABLE IF NOT EXISTS redemption_runs(id INTEGER PRIMARY KEY AUTOINCREMENT,started_at_ms INTEGER NOT NULL,finished_at_ms INTEGER,status TEXT NOT NULL,source TEXT NOT NULL)");
  d.execSQL("CREATE TABLE IF NOT EXISTS redemption_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER NOT NULL,account_id INTEGER,account_name TEXT,player_id TEXT NOT NULL,state TEXT NOT NULL,gift_code TEXT NOT NULL,result TEXT NOT NULL,server_code INTEGER,server_message TEXT,technical_error TEXT,attempted_at_ms INTEGER NOT NULL,FOREIGN KEY(run_id) REFERENCES redemption_runs(id) ON DELETE CASCADE)");
  d.execSQL("CREATE INDEX IF NOT EXISTS idx_attempt_pair ON redemption_attempts(player_id,state,gift_code,result)");d.execSQL("CREATE INDEX IF NOT EXISTS idx_attempt_run ON redemption_attempts(run_id)");
 }
 @Override public void onConfigure(SQLiteDatabase db){super.onConfigure(db);db.setForeignKeyConstraintsEnabled(true);}
 @Override public void onUpgrade(SQLiteDatabase d,int oldV,int newV){if(oldV<4){d.beginTransaction();try{
   try{d.execSQL("ALTER TABLE accounts ADD COLUMN name TEXT");}catch(Exception ignored){} try{d.execSQL("ALTER TABLE accounts ADD COLUMN selected INTEGER NOT NULL DEFAULT 1");}catch(Exception ignored){}
   boolean oldCodes=table(d,"gift_codes")&&!column(d,"gift_codes","first_seen_ms"); if(oldCodes)d.execSQL("ALTER TABLE gift_codes RENAME TO gift_codes_legacy");
   createV4(d); long now=System.currentTimeMillis();
   if(oldCodes){try(Cursor c=d.rawQuery("SELECT code,status FROM gift_codes_legacy",null)){while(c.moveToNext()){ContentValues v=new ContentValues();v.put("code",c.getString(0));v.put("status",c.getString(1));v.put("first_seen_ms",now);v.put("last_seen_ms",now);d.insertWithOnConflict("gift_codes",null,v,SQLiteDatabase.CONFLICT_REPLACE);}}d.execSQL("DROP TABLE gift_codes_legacy");}
   if(table(d,"redemptions")){long run=createRun(d,"MIGRATED");try(Cursor c=d.rawQuery("SELECT player_id,state,gift_code,status,err_code,message FROM redemptions",null)){while(c.moveToNext()){String old=c.getString(3);String result="error".equals(old)?"NETWORK_ERROR":(c.isNull(4)?"API_FAILED":classify(c.getInt(4)));insertAttempt(d,run,null,null,c.getString(0),c.getString(1),c.getString(2),result,c.isNull(4)?null:c.getInt(4),c.getString(5),"error".equals(old)?c.getString(5):null);}}finishRun(d,run,"COMPLETED");}
   d.setTransactionSuccessful();}finally{d.endTransaction();}}
 }
 private boolean table(SQLiteDatabase d,String n){try(Cursor c=d.rawQuery("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",new String[]{n})){return c.moveToFirst();}}
 private boolean column(SQLiteDatabase d,String t,String col){try(Cursor c=d.rawQuery("PRAGMA table_info("+t+")",null)){while(c.moveToNext())if(col.equals(c.getString(1)))return true;}return false;}
 public List<Account> accounts(){List<Account>x=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT id,name,player_id,state,selected FROM accounts ORDER BY id",null)){while(c.moveToNext())x.add(new Account(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getInt(4)!=0));}return x;}
 public List<Account> selectedAccounts(){List<Account>x=new ArrayList<>();for(Account a:accounts())if(a.selected)x.add(a);return x;}
 public boolean addAccount(String name,String p,String s){ContentValues v=new ContentValues();v.put("name",name);v.put("player_id",p);v.put("state",s);v.put("selected",1);return getWritableDatabase().insertWithOnConflict("accounts",null,v,SQLiteDatabase.CONFLICT_IGNORE)!=-1;}
 public void updateAccount(long id,String name,String p,String s){ContentValues v=new ContentValues();v.put("name",name);v.put("player_id",p);v.put("state",s);getWritableDatabase().update("accounts",v,"id=?",new String[]{""+id});}
 public void setSelected(long id,boolean on){ContentValues v=new ContentValues();v.put("selected",on?1:0);getWritableDatabase().update("accounts",v,"id=?",new String[]{""+id});}
 public void selectAll(boolean on){ContentValues v=new ContentValues();v.put("selected",on?1:0);getWritableDatabase().update("accounts",v,null,null);}
 public void deleteAccount(long id){getWritableDatabase().delete("accounts","id=?",new String[]{""+id});}
 public int saveFetchedCodes(List<String> codes){SQLiteDatabase d=getWritableDatabase();long now=System.currentTimeMillis();int n=0;d.beginTransaction();try{for(String raw:codes){String code=raw==null?"":raw.trim();if(code.isEmpty())continue;ContentValues u=new ContentValues();u.put("last_seen_ms",now);u.put("status","active");if(d.update("gift_codes",u,"code=?",new String[]{code})==0){ContentValues v=new ContentValues();v.put("code",code);v.put("first_seen_ms",now);v.put("last_seen_ms",now);v.put("status","active");d.insertOrThrow("gift_codes",null,v);}n++;}d.setTransactionSuccessful();}finally{d.endTransaction();}return n;}
 public List<CodeRow> codes(int limit,String search){List<CodeRow>x=new ArrayList<>();String where=search==null||search.trim().isEmpty()?"":" WHERE code LIKE ?";String[] args=where.isEmpty()?null:new String[]{"%"+search.trim()+"%"};String lim=limit>0?" LIMIT "+limit:"";try(Cursor c=getReadableDatabase().rawQuery("SELECT id,code,first_seen_ms,last_seen_ms,status FROM gift_codes"+where+" ORDER BY last_seen_ms DESC,id DESC"+lim,args)){while(c.moveToNext())x.add(new CodeRow(c.getLong(0),c.getString(1),c.getLong(2),c.getLong(3),c.getString(4)));}return x;}
 public CodeRow code(String code){try(Cursor c=getReadableDatabase().rawQuery("SELECT id,code,first_seen_ms,last_seen_ms,status FROM gift_codes WHERE code=?",new String[]{code})){return c.moveToFirst()?new CodeRow(c.getLong(0),c.getString(1),c.getLong(2),c.getLong(3),c.getString(4)):null;}}
 public int codeCount(){try(Cursor c=getReadableDatabase().rawQuery("SELECT COUNT(*) FROM gift_codes",null)){return c.moveToFirst()?c.getInt(0):0;}}
 public boolean wasAttempted(String p,String s,String code){try(Cursor c=getReadableDatabase().rawQuery("SELECT 1 FROM redemption_attempts WHERE player_id=? AND state=? AND gift_code=? AND result IN ('SUCCESS','ALREADY_RECEIVED','API_FAILED') LIMIT 1",new String[]{p,s,code})){return c.moveToFirst();}}
 public long createRun(String source){return createRun(getWritableDatabase(),source);} private static long createRun(SQLiteDatabase d,String source){ContentValues v=new ContentValues();v.put("started_at_ms",System.currentTimeMillis());v.put("status","RUNNING");v.put("source",source);return d.insertOrThrow("redemption_runs",null,v);}
 public void finishRun(long id,String status){finishRun(getWritableDatabase(),id,status);} private static void finishRun(SQLiteDatabase d,long id,String status){ContentValues v=new ContentValues();v.put("finished_at_ms",System.currentTimeMillis());v.put("status",status);d.update("redemption_runs",v,"id=?",new String[]{""+id});}
 public void record(long run,Account a,String code,String result,Integer serverCode,String message,String technical){insertAttempt(getWritableDatabase(),run,a==null?null:a.id,a==null?null:a.label(),a==null?"":a.playerId,a==null?"":a.state,code,result,serverCode,message,technical);}
 private static void insertAttempt(SQLiteDatabase d,long run,Long aid,String an,String p,String s,String code,String result,Integer sc,String msg,String te){ContentValues v=new ContentValues();v.put("run_id",run);if(aid!=null)v.put("account_id",aid);v.put("account_name",an);v.put("player_id",p);v.put("state",s);v.put("gift_code",code);v.put("result",result);if(sc!=null)v.put("server_code",sc);v.put("server_message",msg);v.put("technical_error",te);v.put("attempted_at_ms",System.currentTimeMillis());d.insertOrThrow("redemption_attempts",null,v);}
 public static String classify(int code){if(code==20000)return "SUCCESS";if(code==40008)return "ALREADY_RECEIVED";return "API_FAILED";}
 public List<RunRow> runs(String filter,int limit){List<RunRow>x=new ArrayList<>();String having="";if("SUCCESSFUL".equals(filter))having=" HAVING network=0 AND failed=0";else if("ISSUES".equals(filter))having=" HAVING network>0 OR failed>0";String q="SELECT r.id,r.started_at_ms,COALESCE(r.finished_at_ms,0),r.status,r.source,COUNT(a.id) total,SUM(CASE WHEN a.result='SUCCESS' THEN 1 ELSE 0 END) success,SUM(CASE WHEN a.result='ALREADY_RECEIVED' THEN 1 ELSE 0 END) received,SUM(CASE WHEN a.result='API_FAILED' THEN 1 ELSE 0 END) failed,SUM(CASE WHEN a.result='NETWORK_ERROR' THEN 1 ELSE 0 END) network,SUM(CASE WHEN a.result='SKIPPED' THEN 1 ELSE 0 END) skipped FROM redemption_runs r LEFT JOIN redemption_attempts a ON a.run_id=r.id GROUP BY r.id"+having+" ORDER BY r.id DESC LIMIT "+Math.max(1,limit);try(Cursor c=getReadableDatabase().rawQuery(q,null)){while(c.moveToNext())x.add(new RunRow(c.getLong(0),c.getLong(1),c.getLong(2),c.getString(3),c.getString(4),c.getInt(5),c.getInt(6),c.getInt(7),c.getInt(8),c.getInt(9),c.getInt(10)));}return x;}
 public RunRow run(long id){for(RunRow r:runs("ALL",500))if(r.id==id)return r;return null;}
 public List<AttemptRow> attempts(long run){List<AttemptRow>x=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT account_name,player_id,state,gift_code,result,server_code,server_message,technical_error,attempted_at_ms FROM redemption_attempts WHERE run_id=? ORDER BY id",new String[]{""+run})){while(c.moveToNext())x.add(new AttemptRow(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.isNull(5)?null:c.getInt(5),c.getString(6),c.getString(7),c.getLong(8)));}return x;}
 public List<AttemptRow> attemptsForCode(String code){List<AttemptRow>x=new ArrayList<>();try(Cursor c=getReadableDatabase().rawQuery("SELECT account_name,player_id,state,gift_code,result,server_code,server_message,technical_error,attempted_at_ms FROM redemption_attempts WHERE gift_code=? ORDER BY id DESC",new String[]{code})){while(c.moveToNext())x.add(new AttemptRow(c.getString(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.isNull(5)?null:c.getInt(5),c.getString(6),c.getString(7),c.getLong(8)));}return x;}
 public void cleanup30Days(){long cutoff=System.currentTimeMillis()-30L*24*60*60*1000;SQLiteDatabase d=getWritableDatabase();d.beginTransaction();try{d.delete("redemption_attempts","attempted_at_ms < ?",new String[]{""+cutoff});d.delete("redemption_runs","id NOT IN (SELECT DISTINCT run_id FROM redemption_attempts) AND started_at_ms < ?",new String[]{""+cutoff});d.delete("gift_codes","last_seen_ms < ?",new String[]{""+cutoff});d.setTransactionSuccessful();}finally{d.endTransaction();}}
}
